"""
sr_core.py
==========
Core Stanley–Reisner algebra operations on Gudhi SimplexTree objects.

All functions are pure (no side-effects beyond optional printing) and work
on any SimplexTree, not just those built from attention matrices.

Sources
-------
Adapted from the persistent_stanley_reisner_theory_tutorial.py notebook
(Section 15 — the cleanest, most correct implementation), with:
  - docstrings reframed in terms of token/attention semantics
  - vertex naming adapted to accept token strings
  - config constants used throughout instead of magic numbers
"""

from __future__ import annotations

import logging
from itertools import combinations
from math import comb
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import gudhi as gd

from sr_attention import config

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Low-level simplex-tree helpers
# ---------------------------------------------------------------------------

def _all_vertices(simplex_tree: gd.SimplexTree) -> List[int]:
    """Return sorted list of all vertex ids in the complex."""
    vs: set[int] = set()
    for simplex, _ in simplex_tree.get_filtration():
        vs.update(simplex)
    return sorted(vs)


def _faces_at_time(simplex_tree: gd.SimplexTree, t: float) -> List[Tuple[int, ...]]:
    """All simplices present at filtration value ≤ t."""
    faces = []
    for simplex, birth in simplex_tree.get_filtration():
        if birth <= t:
            faces.append(tuple(sorted(simplex)))
    return sorted(set(faces))


def _facets_at_time(simplex_tree: gd.SimplexTree, t: float) -> List[Tuple[int, ...]]:
    """Maximal simplices (facets) at time t — those with no strict coface at time t."""
    faces    = _faces_at_time(simplex_tree, t)
    facets   = []
    for s in faces:
        s_set = set(s)
        is_facet = not any(
            len(r) > len(s) and s_set.issubset(r)
            for r in faces
        )
        if is_facet:
            facets.append(s)
    return sorted(facets)


# ---------------------------------------------------------------------------
# f-vector and h-vector
# ---------------------------------------------------------------------------

def compute_persistent_f_vector(
    simplex_tree: gd.SimplexTree, t: float
) -> Dict[int, int]:
    """
    Return the f-vector at threshold t: f[k] = number of k-simplices present.

    In attention context: f[0] = tokens, f[1] = co-attending pairs,
    f[2] = co-attending triples, …
    """
    faces = _faces_at_time(simplex_tree, t)
    fvec: Dict[int, int] = {}
    for s in faces:
        k = len(s) - 1
        fvec[k] = fvec.get(k, 0) + 1
    return dict(sorted(fvec.items()))


def h_vector_and_hilbert(
    simplex_tree: gd.SimplexTree,
    t: Optional[float] = None,
) -> Tuple[List[int], str]:
    """
    Compute h-vector and format the Hilbert series of the SR ring k[Δ_t].

    The h-vector encodes the Hilbert function:
        H_Δ(s) = (Σ h_i s^i) / (1 − s)^d

    Returns
    -------
    h : list[int]
    hilbert_series : str   formatted as "(h₀ + h₁t + …)/(1−t)^d"
    """
    if t is None:
        t = float(max(f for _, f in simplex_tree.get_filtration()))

    faces = _faces_at_time(simplex_tree, t)
    if not faces:
        return [1], "1/(1-t)^1"

    dim = max(len(s) for s in faces) - 1
    d   = dim + 1

    fvec = compute_persistent_f_vector(simplex_tree, t)
    # f[i] = f_{i-1} with the convention f[-1] = 1 (empty face)
    f = [1] + [fvec.get(k, 0) for k in range(d)]

    h = [0] * (d + 1)
    for i in range(d + 1):
        for j in range(i + 1):
            if j < len(f):
                h[i] += ((-1) ** (i - j)) * comb(d - j, i - j) * f[j]

    # Format the Hilbert series string
    terms = []
    for i, c in enumerate(h):
        if c == 0:
            continue
        coeff_str = "" if abs(c) == 1 else str(abs(c))
        var_str   = "" if i == 0 else ("t" if i == 1 else f"t^{i}")
        term = (coeff_str + var_str) or "1"
        terms.append(("-" if c < 0 else "+") + term)

    num = " ".join(terms).lstrip("+").strip() or "0"
    return h, f"({num})/(1-t)^{d}"


# ---------------------------------------------------------------------------
# Stanley–Reisner ideal
# ---------------------------------------------------------------------------

def stanley_reisner_generators(
    simplex_tree: gd.SimplexTree,
    t: Optional[float] = None,
    token_labels: Optional[List[str]] = None,
    print_limit: int = config.SR_PRINT_LIMIT,
    verbose: bool = False,
) -> Tuple[List[Tuple[int, ...]], List[str]]:
    """
    Compute generators of the Stanley–Reisner ideal I(Δ_t).

    I(Δ_t) is generated by squarefree monomials x_{i₁}·…·x_{iₖ} for each
    *minimal* non-face {i₁,…,iₖ} of the complex at time t.

    In attention context: a minimal non-face is a minimal set of tokens that
    *cannot* all mutually attend above threshold τ = 1 − t.

    Parameters
    ----------
    simplex_tree : gd.SimplexTree
    t : float | None
        Filtration snapshot.  Defaults to maximum filtration value.
    token_labels : list[str] | None
        If provided, monomial strings use token text instead of "x_i".
    print_limit : int
        Maximum generators to print when verbose=True.
    verbose : bool

    Returns
    -------
    minimal_non_faces : list of tuples of vertex ids
    monomial_strings  : list of str, matching order
    """
    if t is None:
        t = float(max(f for _, f in simplex_tree.get_filtration()))

    vertices = _all_vertices(simplex_tree)
    n        = len(vertices)

    # Build label map
    if token_labels is not None and len(token_labels) == n:
        _label = lambda v: token_labels[vertices.index(v)]
    else:
        _label = lambda v: f"x_{v}"

    faces = set(_faces_at_time(simplex_tree, t))

    # All non-faces
    non_faces: List[Tuple[int, ...]] = []
    for size in range(1, n + 1):
        for subset in combinations(vertices, size):
            if tuple(sorted(subset)) not in faces:
                non_faces.append(tuple(sorted(subset)))

    # Keep only minimal ones (no proper subset is also a non-face)
    minimal: List[Tuple[int, ...]] = []
    for nf in non_faces:
        nf_set = set(nf)
        if not any(set(other) < nf_set for other in non_faces if other != nf):
            minimal.append(nf)

    # Build monomial strings
    monomials = ["·".join(_label(v) for v in nf) for nf in minimal]

    if verbose:
        tau = 1.0 - t
        print(f"SR ideal I(Δ) at τ={tau:.3f} (t={t:.3f}): {len(minimal)} generators")
        for m in monomials[:print_limit]:
            print(f"  {m}")
        if len(monomials) > print_limit:
            print(f"  … and {len(monomials) - print_limit} more")

    return minimal, monomials


# ---------------------------------------------------------------------------
# Primary decomposition
# ---------------------------------------------------------------------------

def primary_decomposition_from_facets(
    simplex_tree: gd.SimplexTree,
    t: Optional[float] = None,
    token_labels: Optional[List[str]] = None,
    verbose: bool = False,
) -> List[str]:
    """
    Primary decomposition of the SR ideal via facets:

        I(Δ_t) = ⋂_{σ ∈ Facets(Δ_t)} P_σ

    where P_σ = ⟨x_j : j ∉ σ⟩ is the prime ideal "generated by tokens
    NOT in the maximal co-attending group σ".

    In attention terms: each prime component P_σ describes the set of
    tokens that are excluded from the maximal attention clique σ.

    Returns
    -------
    list[str]
        One string per facet, formatted as "⟨label_a, label_b, …⟩".
    """
    if t is None:
        t = float(max(f for _, f in simplex_tree.get_filtration()))

    vertices = _all_vertices(simplex_tree)
    n        = len(vertices)
    facets   = _facets_at_time(simplex_tree, t)

    if token_labels is not None and len(token_labels) == n:
        _label = lambda v: token_labels[vertices.index(v)]
    else:
        _label = lambda v: f"x_{v}"

    components: List[str] = []
    if verbose:
        tau = 1.0 - t
        print(f"Primary decomposition at τ={tau:.3f} (t={t:.3f}):")
        print("  I(Δ_t) = ⋂ P_σ,  where:")

    for facet in facets:
        facet_set = set(facet)
        complement = sorted(v for v in vertices if v not in facet_set)
        ideal_str  = "⟨" + ", ".join(_label(v) for v in complement) + "⟩" \
                     if complement else "⟨1⟩"
        components.append(ideal_str)
        if verbose:
            facet_str = "{" + ", ".join(_label(v) for v in sorted(facet)) + "}"
            print(f"  P_{facet_str} = {ideal_str}")

    return components


# ---------------------------------------------------------------------------
# Utility: build a complex directly from a list of facets
# ---------------------------------------------------------------------------

def build_complex_from_facets(
    facets: List[Sequence[int]],
    filtration: float = 0.0,
) -> gd.SimplexTree:
    """
    Construct a Gudhi SimplexTree from an explicit list of maximal faces.

    Useful for unit tests and toy examples where you already know the facets.
    """
    st = gd.SimplexTree()
    for F in facets:
        st.insert(list(F), filtration=filtration)
    return st
